// lib/nbaPhotos.ts
// Finds a player's NBA.com player number from his name, so we can show
// NBA.com's player photo (the app itself uses ESPN's numbers).
//
// The names and numbers come from lib/nbaPlayers.ts, which is generated by
// scripts/update-nba-ids.mjs. If a name can't be matched with confidence,
// findNbaId returns undefined and the caller uses the ESPN photo instead.

import { NBA_PLAYERS } from './nbaPlayers';

const SUFFIXES = new Set(['jr', 'sr', 'ii', 'iii', 'iv', 'v']);

// "Marvin Bagley III" -> ['marvin', 'bagley'];  "P.J. Washington" -> ['pj', 'washington']
function nameTokens(name: string): string[] {
  const cleaned = name
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '') // strip accents
    .toLowerCase()
    .replace(/[’'`.]/g, '') // drop apostrophes and dots
    .replace(/[^a-z0-9]+/g, ' ') // everything else becomes a space
    .trim();
  const tokens = cleaned ? cleaned.split(' ') : [];
  while (tokens.length > 2 && SUFFIXES.has(tokens[tokens.length - 1])) tokens.pop();
  return tokens;
}

// Built once, when the app loads.
const idByKey = new Map<string, number>();
const ambiguousKeys = new Set<string>(); // two NBA players share this name
const byLastName = new Map<string, Array<{ id: number; first: string }>>();

for (const [id, name] of NBA_PLAYERS) {
  const tokens = nameTokens(name);
  if (tokens.length === 0) continue;
  const key = tokens.join('');
  if (idByKey.has(key) && idByKey.get(key) !== id) ambiguousKeys.add(key);
  else idByKey.set(key, id);

  if (tokens.length >= 2) {
    const last = tokens[tokens.length - 1];
    const list = byLastName.get(last) ?? [];
    list.push({ id, first: tokens[0] });
    byLastName.set(last, list);
  }
}
ambiguousKeys.forEach((k) => idByKey.delete(k));

const cache = new Map<string, number | undefined>();

export function findNbaId(fullName: string): number | undefined {
  if (cache.has(fullName)) return cache.get(fullName);
  const result = lookup(fullName);
  cache.set(fullName, result);
  return result;
}

function lookup(fullName: string): number | undefined {
  const tokens = nameTokens(fullName);
  if (tokens.length === 0) return undefined;

  // 1) Same name (ignoring accents, dots, hyphens, Jr./III).
  const key = tokens.join('');
  if (ambiguousKeys.has(key)) return undefined; // two players share it: don't guess
  const exact = idByKey.get(key);
  if (exact !== undefined) return exact;

  // 2) Careful fallback: same last name, and one first name starts with the
  //    other ("Cam" / "Cameron", "Nic" / "Nicolas") -- only if exactly one fits.
  if (tokens.length < 2) return undefined;
  const first = tokens[0];
  const last = tokens[tokens.length - 1];
  const candidates = (byLastName.get(last) ?? []).filter(
    (c) =>
      Math.min(first.length, c.first.length) >= 3 &&
      (first.startsWith(c.first) || c.first.startsWith(first))
  );
  return candidates.length === 1 ? candidates[0].id : undefined;
}
