// scripts/update-nba-ids.mjs
//
// Downloads NBA.com's list of players (NBA.com player number + name) and saves
// it as lib/nbaPlayers.ts. The app uses that list to show NBA.com's player
// photos (which are updated sooner than ESPN's after trades and signings).
//
// How to run (in Command Prompt, from the project folder):
//     node scripts\update-nba-ids.mjs
//
// If NBA.com blocks the script, there is a backup way: open
// https://www.nba.com/players in your browser, press Ctrl+S, save as
// "Webpage, HTML only" into the project folder as players.html, then run:
//     node scripts\update-nba-ids.mjs players.html
//
// Refresh once or twice a year (e.g. when rookies arrive). A player who isn't
// on the list just keeps their ESPN photo -- nothing breaks.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const OUT_FILE = join(dirname(fileURLToPath(import.meta.url)), '..', 'lib', 'nbaPlayers.ts');
const NBA_PLAYERS_PAGE = 'https://www.nba.com/players';
const BROWSER_UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';
const MIN_PLAYERS = 300; // sanity check: refuse to write a file from a partial list

const ID_KEYS = ['PERSON_ID', 'personId', 'PLAYER_ID', 'playerId'];

function collectFromJson(node, found) {
  if (Array.isArray(node)) {
    node.forEach((n) => collectFromJson(n, found));
    return;
  }
  if (!node || typeof node !== 'object') return;

  const idKey = ID_KEYS.find((k) => Number.isInteger(Number(node[k])) && Number(node[k]) > 0);
  if (idKey) {
    const first = node.PLAYER_FIRST_NAME ?? node.playerFirstName ?? node.firstName;
    const last = node.PLAYER_LAST_NAME ?? node.playerLastName ?? node.lastName;
    const full = node.PLAYER_NAME ?? node.playerName ?? node.displayName ?? node.name;
    const name = first && last ? `${first} ${last}` : typeof full === 'string' ? full : null;
    if (name && /[a-z]/i.test(name)) found.set(Number(node[idKey]), name);
  }
  Object.values(node).forEach((v) => collectFromJson(v, found));
}

export function parseNbaPlayers(html) {
  const found = new Map(); // NBA id -> name

  // 1) The page's embedded data (usually has every player).
  const m = html.match(/<script id="__NEXT_DATA__"[^>]*>([\s\S]*?)<\/script>/);
  if (m) {
    try {
      collectFromJson(JSON.parse(m[1]), found);
    } catch {
      /* fall through to the link scan */
    }
  }

  // 2) Backup: player links like /player/2544/lebron-james/ in the page itself.
  const linkRe = /\/player\/(\d+)\/([a-z0-9'’.-]+?)\/?["'<\s)]/gi;
  let lm;
  while ((lm = linkRe.exec(html)) !== null) {
    const id = Number(lm[1]);
    if (!found.has(id)) found.set(id, lm[2].replace(/-/g, ' '));
  }
  return found;
}

async function loadNbaPlayers(localFile) {
  if (localFile) {
    console.log(`Reading NBA.com player list from ${localFile} ...`);
    return parseNbaPlayers(readFileSync(localFile, 'utf8'));
  }
  console.log('Downloading NBA.com player list ...');
  const res = await fetch(NBA_PLAYERS_PAGE, {
    headers: { 'User-Agent': BROWSER_UA, Accept: 'text/html,application/xhtml+xml' },
    signal: AbortSignal.timeout(30000),
  });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return parseNbaPlayers(await res.text());
}

export function buildFile(players) {
  const rows = [...players.entries()]
    .sort((a, b) => a[1].localeCompare(b[1]))
    .map(([id, name]) => `  [${id}, ${JSON.stringify(name)}],`)
    .join('\n');
  return `// lib/nbaPlayers.ts
// NBA.com's player list (NBA.com player number + name), used to show NBA.com's
// player photos.
//
// AUTO-GENERATED by scripts/update-nba-ids.mjs on ${new Date().toISOString().slice(0, 10)} -- do not edit by hand.
// Run \`node scripts\\update-nba-ids.mjs\` to refresh (once or twice a year, e.g.
// when rookies arrive).
export const NBA_PLAYERS: ReadonlyArray<readonly [number, string]> = [
${rows}
];
`;
}

async function main() {
  let players;
  try {
    players = await loadNbaPlayers(process.argv[2]);
  } catch (err) {
    console.error(`\nCould not get NBA.com's player list (${err.message}).`);
    console.error('Try the backup method described at the top of this script, or tell Claude what you see.');
    process.exit(1);
  }
  console.log(`  found ${players.size} NBA.com players`);

  if (players.size < MIN_PLAYERS) {
    console.error(`\nThe list looks incomplete (needs at least ${MIN_PLAYERS} players). Nothing was changed.`);
    process.exit(1);
  }

  writeFileSync(OUT_FILE, buildFile(players), 'utf8');
  console.log(`\nDone. Saved ${players.size} players to lib/nbaPlayers.ts`);

  // Quick spot check so you can see the names look right.
  const sample = [...players.values()].filter((n) => /lebron|giannis|jaylen brown|dort/i.test(n));
  if (sample.length) console.log(`Spot check: ${sample.join(', ')}`);
}

// Only run when started from the command line (so tests can import it).
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main();
}
